Adds unit test coverage for audio query
mhbuehler/GenAIComps pull request #14
Opened 2024-12-05 22:47 UTC by mhbuehler

## Description

Adds a test to test_multimodalqna_gateway.py for the new functionality.

## Issues

[RFC](https://github.com/opea-project/docs/blob/main/community/rfcs/24-10-02-GenAIExamples-001-Image_and_Audio_Support_in_MultimodalQnA.md)

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Others (enhancement, documentation, validation, etc.)

## Dependencies

N/A

## Tests

Ran the new test locally and verified the assertion passes

2024-12-05 23:10 UTC, dmsuehir requested changes

2024-12-05 23:10 UTC, dmsuehir commented on tests/cores/mega/test_multimodalqna_gateway.py
> +        prompt, images = self.gateway._handle_message(messages)
After Omar's updates, handle_message now returns `prompt, b64_types` ([source](https://github.com/mhbuehler/GenAIComps/blob/mmqna-audio-query/comps/cores/mega/gateway.py#L963)) and you could also have an assert checking for `b64_types["audio"] == you`

2024-12-05 23:10 UTC, dmsuehir commented on tests/cores/mega/test_multimodalqna_gateway.py
> +            opea_microservices["lvm"]).add(opea_microservices["asr"])
I don't think this is right, because it's going to try to call ASR after the LVM and the input/outputs won't match up, and that's also not the sequence that we want.

Remove this and then set this env var with the ASR port before the gateway is created.
```
os.environ["ASR_SERVICE_PORT"] = 8086
```

2024-12-05 23:10 UTC, dmsuehir commented on tests/cores/mega/test_multimodalqna_gateway.py
> +@register_microservice(name="asr", host="0.0.0.0", port=3001, endpoint="/v1/audio/transcriptions")
Use another port that's not the real ASR port. For example they are already using 8083, 8084, 8085 for the other microservices, so we could use 8086 for ASR.

```suggestion
@register_microservice(name="asr", host="0.0.0.0", port=8086, endpoint="/v1/audio/transcriptions")
```

2024-12-06 17:20 UTC, dmsuehir commented on tests/cores/mega/test_multimodalqna_gateway.py
> +            opea_microservices["lvm"])
You could put the formatting of this back to how it was so that it's one less diff

2024-12-06 17:31 UTC, ashahba approved these changes

2024-12-06 17:33 UTC, dmsuehir approved these changes

2024-12-06 17:34 UTC, merged